# Generated by Django 3.0.8 on 2024-02-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall_number', models.IntegerField(unique=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
