# Generated by Django 3.0.8 on 2024-02-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='stall',
            old_name='votes',
            new_name='total_votes',
        ),
        migrations.AlterField(
            model_name='stall',
            name='stall_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
