# Generated by Django 3.0.8 on 2024-02-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20240217_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='selected_stalls',
            field=models.ManyToManyField(to='main.Stall'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stall_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voting_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
